#include "ams/compiler/CodeGen.hpp"
#include <vector>

// ============================================================
// CodeGen Implementation : Generates C++ Monitoring Program
// ============================================================

std::any CodeGen::visitProgram(AMSParser::ProgramContext *ctx) {
    // Write C++ file header with all needed includes
    out << "// Generated by AutomonScript Compiler" << std::endl;
    out << "#include <iostream>" << std::endl;
    out << "#include <fstream>" << std::endl;
    out << "#include <string>" << std::endl;
    out << "#include <vector>" << std::endl;
    out << "#include <regex>" << std::endl;
    out << "#include <chrono>" << std::endl;
    out << "#include <thread>" << std::endl;
    out << "#include <map>" << std::endl;
    out << "#include <cstdlib>" << std::endl;
    out << std::endl;

    // Helper function for logging to file
    out << "void logToFile(const std::string& file, const std::string& msg) {" << std::endl;
    out << "    std::ofstream ofs(file, std::ios::app);" << std::endl;
    out << "    if (ofs.is_open()) {" << std::endl;
    out << "        ofs << msg << std::endl;" << std::endl;
    out << "        std::cout << \"[LOG] Written to: \" << file << std::endl;" << std::endl;
    out << "    }" << std::endl;
    out << "}" << std::endl;
    out << std::endl;

    // Main function start
    out << "int main() {" << std::endl;
    out << "    std::cout << \"========================================\" << std::endl;" << std::endl;
    out << "    std::cout << \" AutomonScript Compiled Monitor Active \" << std::endl;" << std::endl;
    out << "    std::cout << \"========================================\" << std::endl;" << std::endl;
    out << std::endl;
    out << "    // Variable storage" << std::endl;
    out << "    std::map<std::string, std::string> vars;" << std::endl;
    out << std::endl;

    // Visit all child statements
    std::any result = visitChildren(ctx);

    // Main function end
    out << std::endl;
    out << "    std::cout << \"\\n[ENGINE] Monitoring cycle complete.\" << std::endl;" << std::endl;
    out << "    return 0;" << std::endl;
    out << "}" << std::endl;

    return result;
}

std::any CodeGen::visitMonitorStmt(AMSParser::MonitorStmtContext *ctx) {
    std::string source = stripQuotes(ctx->STRING()->getText());
    out << "    // MONITOR: " << source << std::endl;
    out << "    std::cout << \"[MONITOR] Scanning data source: " << source << "\" << std::endl;" << std::endl;
    out << "    std::ifstream monitor_file(\"" << source << "\");" << std::endl;
    out << "    std::vector<std::string> monitor_lines;" << std::endl;
    out << "    if (monitor_file.is_open()) {" << std::endl;
    out << "        std::string line;" << std::endl;
    out << "        while (std::getline(monitor_file, line)) { monitor_lines.push_back(line); }" << std::endl;
    out << "        monitor_file.close();" << std::endl;
    out << "        std::cout << \"[MONITOR] Loaded \" << monitor_lines.size() << \" lines from " << source << "\" << std::endl;" << std::endl;
    out << "    } else {" << std::endl;
    out << "        std::cout << \"[MONITOR] Warning: Could not open " << source << " (will simulate)\" << std::endl;" << std::endl;
    out << "    }" << std::endl;
    out << std::endl;
    return nullptr;
}

std::any CodeGen::visitWatchStmt(AMSParser::WatchStmtContext *ctx) {
    std::string type = ctx->ID()->getText();
    std::string source = stripQuotes(ctx->STRING()->getText());
    out << "    // WATCH " << type << ": " << source << std::endl;
    out << "    std::cout << \"[WATCH] Registered " << type << " watcher for: " << source << "\" << std::endl;" << std::endl;
    out << std::endl;
    return nullptr;
}

std::any CodeGen::visitSetStmt(AMSParser::SetStmtContext *ctx) {
    std::string varName = ctx->ID()->getText();
    std::string val = ctx->value()->getText();
    // Strip quotes for string values
    std::string cleanVal = stripQuotes(val);

    out << "    // SET " << varName << " = " << val << std::endl;
    out << "    vars[\"" << varName << "\"] = \"" << cleanVal << "\";" << std::endl;
    out << "    std::cout << \"[SET] " << varName << " = " << cleanVal << "\" << std::endl;" << std::endl;
    out << std::endl;
    return nullptr;
}

std::any CodeGen::visitRuleBlock(AMSParser::RuleBlockContext *ctx) {
    std::string ruleName = ctx->ID()->getText();
    out << std::endl;
    out << "    // ---- RULE: " << ruleName << " ----" << std::endl;
    out << "    std::cout << \"\\n[RULE] Evaluating: " << ruleName << "\"";

    // Optional severity
    if (ctx->severity()) {
        std::string level = ctx->severity()->severityLevel()->getText();
        out << " << \" [SEVERITY: " << level << "]\"";
    }
    out << " << std::endl;" << std::endl;

    out << "    {" << std::endl;
    out << "        int match_count = 0;" << std::endl;
    out << "        int threshold = 1;" << std::endl;

    // Visit WHEN clauses
    for (auto wc : ctx->whenClause()) {
        visit(wc);
    }

    // Visit optional IF clause
    if (ctx->ifClause()) {
        visit(ctx->ifClause());
    }

    // Visit the DO block
    visit(ctx->doBlock());

    out << "    }" << std::endl;
    return nullptr;
}

std::any CodeGen::visitSeverity(AMSParser::SeverityContext *ctx) {
    // Handled inline in visitRuleBlock
    return nullptr;
}

std::any CodeGen::visitWhenClause(AMSParser::WhenClauseContext *ctx) {
    visit(ctx->eventPattern());
    if (ctx->timeWindow()) {
        visit(ctx->timeWindow());
    }
    return nullptr;
}

std::any CodeGen::visitEventPattern(AMSParser::EventPatternContext *ctx) {
    std::string pattern = stripQuotes(ctx->STRING()->getText());
    bool isRegex = (ctx->getText().find("regex") != std::string::npos);

    if (isRegex) {
        out << "        // WHEN regex(\"" << pattern << "\")" << std::endl;
        out << "        std::regex rule_pattern(\"" << pattern << "\");" << std::endl;
        out << "        for (const auto& line : monitor_lines) {" << std::endl;
        out << "            if (std::regex_search(line, rule_pattern)) { match_count++; }" << std::endl;
        out << "        }" << std::endl;
        out << "        std::cout << \"  [WHEN] Regex matches found: \" << match_count << std::endl;" << std::endl;
    } else {
        out << "        // WHEN \"" << pattern << "\"" << std::endl;
        out << "        for (const auto& line : monitor_lines) {" << std::endl;
        out << "            if (line.find(\"" << pattern << "\") != std::string::npos) { match_count++; }" << std::endl;
        out << "        }" << std::endl;
        out << "        std::cout << \"  [WHEN] Pattern matches found: \" << match_count << std::endl;" << std::endl;
    }
    return nullptr;
}

std::any CodeGen::visitTimeWindow(AMSParser::TimeWindowContext *ctx) {
    std::vector<antlr4::tree::TerminalNode*> ints = ctx->INT();
    std::string unit = ctx->timeUnit()->getText();

    if (ints.size() == 2) {
        std::string count = ints[0]->getText();
        std::string duration = ints[1]->getText();
        out << "        // OCCURS " << count << " TIMES IN " << duration << " " << unit << std::endl;
        out << "        threshold = " << count << ";" << std::endl;
        out << "        std::cout << \"  [TIME] Threshold: \" << threshold << \" events in " << duration << " " << unit << "\" << std::endl;" << std::endl;
    } else if (ints.size() == 1) {
        std::string duration = ints[0]->getText();
        out << "        // WITHIN/IN " << duration << " " << unit << std::endl;
        out << "        std::cout << \"  [TIME] Window: " << duration << " " << unit << "\" << std::endl;" << std::endl;
    }
    return nullptr;
}

std::any CodeGen::visitIfClause(AMSParser::IfClauseContext *ctx) {
    out << "        // IF condition evaluation" << std::endl;
    out << "        std::cout << \"  [IF] Evaluating condition\" << std::endl;" << std::endl;
    out << "        bool condition_met = true; // Simulated" << std::endl;
    visit(ctx->condition());
    return nullptr;
}

std::any CodeGen::visitCondition(AMSParser::ConditionContext *ctx) {
    if (ctx->ID()) {
        std::string field = ctx->ID()->getText();
        std::string op = ctx->compOp()->getText();
        std::string val = ctx->value()->getText();
        std::string cleanVal = stripQuotes(val);
        out << "        std::cout << \"    Condition: " << field << " " << op << " " << cleanVal << "\" << std::endl;" << std::endl;
    }
    // Visit sub-conditions for AND/OR/NOT
    for (auto sub : ctx->condition()) {
        visit(sub);
    }
    return nullptr;
}

std::any CodeGen::visitDoBlock(AMSParser::DoBlockContext *ctx) {
    out << "        // Execute actions if rule triggers" << std::endl;
    out << "        if (match_count >= threshold) {" << std::endl;
    out << "            std::cout << \"  [TRIGGERED] Rule conditions met!\" << std::endl;" << std::endl;

    for (auto action : ctx->action()) {
        visit(action);
    }

    out << "        } else {" << std::endl;
    out << "            std::cout << \"  [OK] Rule conditions not met (\" << match_count << \"/\" << threshold << \" matches)\" << std::endl;" << std::endl;
    out << "        }" << std::endl;
    return nullptr;
}

std::any CodeGen::visitAction(AMSParser::ActionContext *ctx) {
    std::string arg = stripQuotes(ctx->STRING()->getText());
    std::string text = ctx->getText();

    if (text.find("SEND_EMAIL") != std::string::npos) {
        out << "            std::cout << \"    [ACTION] SEND_EMAIL to: " << arg << "\" << std::endl;" << std::endl;
    } else if (text.find("BLOCK_IP") != std::string::npos) {
        out << "            std::cout << \"    [ACTION] BLOCK_IP: " << arg << "\" << std::endl;" << std::endl;
    } else if (text.find("EXECUTE_SCRIPT") != std::string::npos) {
        out << "            std::cout << \"    [ACTION] EXECUTE_SCRIPT: " << arg << "\" << std::endl;" << std::endl;
        out << "            std::system(\"" << arg << "\");" << std::endl;
    } else if (text.find("CALL_API") != std::string::npos) {
        out << "            std::cout << \"    [ACTION] CALL_API: " << arg << "\" << std::endl;" << std::endl;
    } else if (text.find("ALERT") != std::string::npos) {
        out << "            std::cout << \"    [ACTION] ALERT: " << arg << "\" << std::endl;" << std::endl;
    } else if (text.find("LOG") != std::string::npos) {
        out << "            logToFile(\"" << arg << "\", \"[ALERT] Rule triggered\");" << std::endl;
    } else if (text.find("CONSOLE") != std::string::npos) {
        out << "            std::cout << \"" << arg << "\" << std::endl;" << std::endl;
    }
    return nullptr;
}